# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: postgresql
  encoding: unicode
  database: code-wanderer-backend_development
  pool: 5
  username: mphmacbookpro
  password: news1411
  timeout: 5000
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: code-wanderer-backend_test
  pool: 5
  username: mphmacbookpro
  password: news1411
  timeout: 5000
  port: 5433
  

